### ISSUE TITLE
Create Tests for Existing Pages

### ISSUE THREAD

**Issue by lauragift21** [datopian/portal#10]
We want to test out the main pages of the app (home, showcase) using the TDD approach.

### Acceptance
* [ ] Test exists for the main pages of the app.

### Tasks
* [x] Research how testing works in Next.js
* [ ] Write tests for existing features of the app
