### ISSUE TITLE
GraphQL Experiment - Apollo + Next.js

### ISSUE THREAD

**Issue by lauragift21** [datopian/portal#13]
Research how to use apollo as the primary data source for Next.js apps.

### Acceptance Criteria
* [ ] We have a demo app showing how to work with Apollo and Next.js with local data and external data sources. 

### Task

* [x] Set up a demo project with Apollo and Next.js
* [ ] Convert external rest api into graphql using apollo data source

**Comment by lauragift21** [comment]
## Notes from GraphQL Experiment

## Why?

We want to have a single source of truth for all of the local and remote data in our application.

## Analysis

### How do we use demo.ckan.org API with Apollo?

- It's easy to adopt Apollo incrementally, meaning you can set it up alongside an existing solution (such as a REST API) and migrate functionality at your convenience.

- Apollo provides a `DataSource` class that we can extend to handle interaction logic for a particular type of data source that we can use to create a new data source for GraphQL API which we can then consume on the client-side.

connect a Rest API (demo.ckan.org) with `apollo-datasource-rest`-> Consume on the frontend

**Comment by anuveyatsu** [comment]
Closing this as FIXED. See #29 and #32  for how we have implemented this.
