### ISSUE TITLE
CI / CD setup

### ISSUE THREAD

**Issue by rufuspollock** [datopian/portal#19]
## Acceptance criteria

* [x] When a new commit is pushed to master branch, it is automatically deployed somewhere so we can use it as a live demo internally and for testing
* [x] When I review a pull request, I can see live demo of the changes

## Tasks

* [x] Setup Vercel with this repo 
* [x] Add domain address in the README

**Comment by anuveyatsu** [comment]
FIXED, live DEMO: https://portal.datopian1.now.sh
