### ISSUE TITLE
Setup code formatter - prettier

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/portal#22]
## Acceptance criteria

* [x] I can run `yarn format` to format my code
* [x] When I commit, it auto formats my code

## Tasks

* [x] Install and setup prettier
* [x] Setup pre commit hooks, see example here https://gitlab.com/datopian/clients/national-grid/-/blob/staging/package.json#L51-58

**Comment by lauragift21** [comment]
@anuveyatsu I can take this and #21  on if you don't mind

**Comment by anuveyatsu** [comment]
@lauragift21 sure - just assigned it to you 👍
