### ISSUE TITLE
Try out apollo graphql server for "Local DB" (local state and remote data cache)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/portal#24]
Follow up to research data layer #18 

## Acceptance

* [x] We have app set up with local DB with graphql API (e.g. apollo)
* [x] renderers (react components) access this layer (with some fixture data in it)

## Tasks

* [x] Setup apollo client by looking at this example https://github.com/vercel/next.js/tree/canary/examples/with-apollo/lib
* [x] Mock our API by stubbing `typeDefs` and `resolvers`, e.g., we can do it for search page
* [x] Refactor `/pages/_app.tsx` to use apollo
* [x] Refactor `/pages/search.tsx` to use apollo

Extra:

* [x] Refactor Dataset page to use apollo
* [x] Refactor Resource page to use apollo

## Analysis

Mocking apollo server according to https://www.robinwieruch.de/graphql-server-mock-apollo-client:

1. `/pages/_app.tsx`:

```javascript
import { ApolloProvider } from '@apollo/react-hooks'
import { useApollo } from '../lib/apolloClient'

export default function App({ Component, pageProps }) {
  const apolloClient = useApollo(pageProps.initialApolloState)

  return (
    <ApolloProvider client={apolloClient}>
      <Component {...pageProps} />
    </ApolloProvider>
  )
}
```

2. `/lib/apolloClient`:

```javascript
import { useMemo } from 'react';
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { SchemaLink } from 'apollo-link-schema';
import { makeExecutableSchema } from 'graphql-tools';

let apolloClient;

const typeDefs = `
  type Query {
    search(query: SearchQuery!): Response!
  }

  type SearchQuery {
    q: String!
    fq: String!
    sort: String!
    rows: Int!
    start: Int!
    facet: String!
    include_drafts: Boolean!
    include_private: Boolean!
    use_default_schema: Boolean!
  }

  type Response {
    success: Boolean!
    result: Result!
  }

  type Result {
    count: Int!
    sort: String!
    facets: String!
    search_facets: String!
    results: [Package!]!
  }

  type Package {
    name: String!
    title: String!
    notes: String!
    resources: [Resource!]!
    organization: Organization!
    metadata_created: String!
    metadata_modified: String!
  }

  type Resource {
    name: String!
    id: String!
    title: String!
    format: String!
    created: String!
    last_modified: String!
    datastore_active: Boolean!
    url: String!
  }

  type Organization {
    name: String!
    title: String!
    description: String!
    created: String!
    image_url: String!
  }
`;

const resolvers = {
  Query: {
    search: (parent, { query }) => ({
      success: true,
      result: {
        count: 2,
        sort: 'score desc, metadata_modified desc',
        facets: {},
        results: [
          {
            name: 'gdp',
            title: 'Country, Regional and World GDP (Gross Domestic Product)',
            notes:
              'Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV.',
            resources: [
              {
                name: 'gdp',
                id: 'gdp',
                title: 'GDP data',
                format: 'csv',
                created: '2019-03-07T12:00:36.273495',
                last_modified: '2020-05-07T12:00:36.273495',
                datastore_active: false,
                url: 'http://mock.filestore/gdp.csv',
              },
            ],
            organization: {
              title: 'World Bank',
              name: 'world-bank',
              description:
                'The World Bank is an international financial institution that provides loans and grants to the governments of poorer countries for the purpose of pursuing capital projects.',
              created: '2019-03-07T11:51:13.758844',
              image_url:
                'https://github.com/datahq/frontend/raw/master/public/img/avatars/world-bank.jpg',
            },
            metadata_created: '2019-03-07T11:56:19.696257',
            metadata_modified: '2019-03-07T12:03:58.817280',
          },
          {
            name: 'population',
            title: 'World population data',
            notes:
              'Population figures for countries, regions (e.g. Asia) and the world. Data comes originally from World Bank and has been converted into standard CSV.',
            resources: [
              {
                name: 'population',
                id: 'population',
                title: 'Population data',
                format: 'csv',
                created: '2019-03-07T12:00:36.273495',
                last_modified: '2020-05-07T12:00:36.273495',
                datastore_active: true,
                url: 'http://mock.filestore/population.csv',
              },
            ],
            organization: {
              title: 'World Bank',
              name: 'world-bank',
              description:
                'The World Bank is an international financial institution that provides loans and grants to the governments of poorer countries for the purpose of pursuing capital projects.',
              created: '2019-03-07T11:51:13.758844',
              image_url:
                'https://github.com/datahq/frontend/raw/master/public/img/avatars/world-bank.jpg',
            },
          },
        ],
        search_facets: {},
      },
    }),
  },
};

const executableSchema = makeExecutableSchema({
  typeDefs,
  resolvers,
});

const link = new SchemaLink({ schema: executableSchema });

function createApolloClient() {
  return new ApolloClient({
    ssrMode: typeof window === 'undefined',
    link,
    cache: new InMemoryCache(),
  });
}

export function initializeApollo(initialState = null) {
  const _apolloClient = apolloClient ?? createApolloClient();

  // If your page has Next.js data fetching methods that use Apollo Client, the initial state
  // gets hydrated here
  if (initialState) {
    _apolloClient.cache.restore(initialState);
  }
  // For SSG and SSR always create a new Apollo Client
  if (typeof window === 'undefined') return _apolloClient;
  // Create the Apollo Client once in the client
  if (!apolloClient) apolloClient = _apolloClient;

  return _apolloClient;
}

export function useApollo(initialState) {
  const store = useMemo(() => initializeApollo(initialState), [initialState]);
  return store;
}
```

3. `/pages/search.tsx`:

```javascript
import { GetServerSideProps } from 'next';
import querystring from 'querystring';
import config from '../config';
import utils from '../utils';
import Head from 'next/head';
import Nav from '../components/home/Nav';
import Input from '../components/search/Input';
import Total from '../components/search/Total';
import Sort from '../components/search/Sort';
import List, { DEFAULT_SEARCH_QUERY } from '../components/search/List';
import { initializeApollo } from '../lib/apolloClient';

function Search() {
  return (
    <>
      <Head>
        <title>Portal | Search</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="p-6">
        <Input />
        <Total />
        <Sort />
        <List />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const apolloClient = initializeApollo();

  await apolloClient.query({
    query: DEFAULT_SEARCH_QUERY,
  });

  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
    },
    unstable_revalidate: 1,
  };
};

export default Search;
```

4. `/components/search/List.tsx`:

```javascript
import Item from './Item';
import { useQuery } from '@apollo/react-hooks';
import gql from 'graphql-tag';

export const DEFAULT_SEARCH_QUERY = gql`
  search($query: SearchQuery!) {
    result {
      results
    }
  }
`;

export default function List() {
  const { loading, error, data, fetchMore, networkStatus } = useQuery(
    DEFAULT_SEARCH_QUERY,
    {
      // Setting this value to true will make the component rerender when
      // the "networkStatus" changes, so we are able to know if it is fetching
      // more data
      notifyOnNetworkStatusChange: true,
    }
  );

  if (error) return <ErrorMessage message="Error loading posts." />;
  if (loading) return <div>Loading</div>;

  const { result } = data;

  return (
    <ul>
      {result.map((datapackage, index) => (
        <Item datapackage={datapackage} key={index} />
      ))}
    </ul>
  );
}
```

Implementing this is returning the following error:

```bash
🌵 portal yarn dev
yarn run v1.22.0
$ next dev
ready - started server on http://localhost:3000
> Using external babel configuration
> Location: "/Volumes/128gb-ssd/projects/portal/.babelrc"
error - ./node_modules/simple-git/src/lib/git-executor.js
Module not found: Can't resolve 'child_process' in '/Volumes/128gb-ssd/projects/portal/node_modules/simple-git/src/lib'
wait  - compiling...
error - ./node_modules/simple-git/src/lib/git-executor.js
Module not found: Can't resolve 'child_process' in '/Volumes/128gb-ssd/projects/portal/node_modules/simple-git/src/lib'
^C
```

**Comment by anuveyatsu** [comment]
Related pull request - #27 

I'd consider this ticket as done but I'm doing some extra tasks now.

**Comment by anuveyatsu** [comment]
FIXED:

- we have created mocked graphql server;
- we have created Apollo client that uses the mocked server;
- we have refactored all dynamic pages to use Apollo for data fetching from local DB.

All work has been committed to the branch and the PR was opened - https://github.com/datopian/portal/pull/27 however, we are not merging into master as we're continuing the work in the same branch (connecting the actual CKAN API).
