### ISSUE TITLE
No placeholders / hard code in the components

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/portal#25]
## Acceptance criteria

* [x] Home page's recent datasets section is dynamic

## Tasks

* [x] Add mocks for getting recent datasets
* [x] Remove hardcoded recent datasets section from https://github.com/datopian/portal/blob/master/components/home/Recent.tsx and make sure it runs from the mocks

**Comment by anuveyatsu** [comment]
@lauragift21 please have a look at this one

**Comment by lauragift21** [comment]
Sure! looking into it.

**Comment by lauragift21** [comment]
Hi @anuveyatsu. Working on this which of these is the right endpoint for recent datasets?

**Comment by anuveyatsu** [comment]
@lauragift21 I believe you need recently created datasets, in that case you need:

https://demo.ckan.org/api/3/action/package_search?sort=metadata_created%20desc

**Comment by anuveyatsu** [comment]
@lauragift21 it is now deployed - https://portal.datopian1.now.sh/
However, you can see that your solution doesn't consider situations when you get more than 3 datasets. I'm going to fix it by changing the query param.

**Comment by anuveyatsu** [comment]
FIXED and deployed to https://portal.datopian1.now.sh/
