### ISSUE TITLE
Connect CKAN API into Apollo GraphQL client

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/portal#29]
Job story:

When building frontend for my CKAN portal using this framework I want to configure my CKAN backend so that all the metadata shows up in the portal

## Acceptance criteria

* [x] Demo portal site working with CKAN API e.g. demo.ckan.org - http://portal.datopian1.now.sh/
* [x] Docs in README for how to configure your CKAN backend - https://github.com/datopian/portal/commit/90f3fc0f68dd862db8f3cc7386025a83505974a1
  * [x] Notes on what is NOT supported atm https://github.com/datopian/portal/commit/b19a37e21a93a2d43f5ec4fe3ff438f7994a6324
* [ ] (v brief) document your learnings about apollo and share in issue / with team

## Tasks

* [x] Connect CKAN API into Apollo GraphQL client
  * [x] Initial setup work
  * [x] Search page refactoring
  * [x] Dataset page refactoring
  * [x] Resource page refactoring

## Analysis

There are 2 ways of connecting CKAN API with Apollo:

1. Build Apollo Server with data source as CKAN API.
2. Use REST link to connect REST API to Apollo client so no server is needed: https://www.apollographql.com/docs/link/links/rest/

Apollo client in Next.js (assuming there is a graphql server):

```javascript=
// `/lib/apolloClient.js`
import { useMemo } from 'react';
import getConfig from 'next/config';
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';

let apolloClient;

function createApolloClient() {
  const { publicRuntimeConfig } = getConfig();
  return new ApolloClient({
    ssrMode: typeof window === 'undefined',
    link: x // This is where we connect the API...,
    cache: new InMemoryCache(),
  });
}

export function initializeApollo(initialState = null) {
  const _apolloClient = apolloClient ?? createApolloClient();

  // If your page has Next.js data fetching methods that use Apollo Client, the initial state
  // gets hydrated here
  if (initialState) {
    _apolloClient.cache.restore(initialState);
  }
  // For SSG and SSR always create a new Apollo Client
  if (typeof window === 'undefined') return _apolloClient;
  // Create the Apollo Client once in the client
  if (!apolloClient) apolloClient = _apolloClient;

  return _apolloClient;
}

export function useApollo(initialState) {
  const store = useMemo(() => initializeApollo(initialState), [initialState]);
  return store;
}

```

### Apollo Server

server:

```javascript=
const { ApolloServer } = require('apollo-server');
const typeDefs = require('./schema');
const { createStore } = require('./utils');

const ckanAPI = require('...');

const store = createStore();

const server = new ApolloServer({
  typeDefs,
  dataSources: () => ({
    ckanAPI: new ckanAPI()
  })
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

ckanAPI:

```javascript=
const { DataSource } = require('apollo-datasource');

class ckanAPI extends DataSource {
  constructor({ store }) {
    super();
    this.store = store;
  }

  /**
   * This is a function that gets called by ApolloServer when being setup.
   * This function gets called with the datasource config including things
   * like caches and context. We'll assign this.context to the request context
   * here, so we can know about the user making requests
   */
  initialize(config) {
    this.context = config.context;
  }

  
  // Search method that searches CKAN portal
  async search({ query }) {
    // ...
    return result;
  }

  async getDataPackage({ name }) {
    // ...
    return datapackage;
  }
}

module.exports = ckanAPI;
```

schema:

```javascript=
const { gql } = require('apollo-server');

const typeDefs = gql`
  type DataPackage {
    id: ID!
    name: String
    title: String
    resources: Resources
  }
`;

module.exports = typeDefs;
```

### Without Apollo Server

References:

- Example projects:
  - https://github.com/apollographql/apollo-link-rest/tree/master/examples/simple
  - https://github.com/apollographql/apollo-link-rest/tree/master/examples/advanced
- Official docs: https://www.apollographql.com/docs/link/links/rest/

**Comment by anuveyatsu** [comment]
Closing this as FIXED:

- CKAN API is connected to Apollo GraphQL client
- Deployed to https://portal.datopian1.now.sh/
