### ISSUE TITLE
Connect CMS (WordPress) API to Apollo client

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/portal#32]
As next step after #29 we want to connect second data source which is WordPress REST API to our Apollo GraphQL client.

## Acceptance criteria

* [x] I can connect a WordPress.com instance by defining `CMS` env var.
* [x] All my posts appear at `/blog/`
* [x] All my pages appear at `/:slug`
  * appars at `/p/:slug`

## Tasks

* [x] Create components for rendering static content: `/components/static/Page.tsx` and `/components/static/Post.tsx`
* [x] Create NextJS page for both page and post types: `/pages/[page]/index.tsx` and `/pages/blog/[post]/index.tsx`
* [x] Setup Apollo client to connect multiple REST APIs: https://www.apollographql.com/docs/link/links/rest/#multiple-endpoints
* [x] Setup NextJS pages to fetch WordPress API
* [x] Setup components to use the content from Apollo cache

**Comment by anuveyatsu** [comment]
@rufuspollock this is now deployed at https://portal.datopian1.now.sh/blog

Points to note:

- We need to think about DEMO wordpress site. I hope it's ok to use oddk WP for the demo here.
- For the static pages (not posts, eg, about page) from WordPress, we can't have path like `/:slug` because we also have `/search` and `/@org`. Here I've implemented it as `/p/:slug` but if you have a suggestion please let me know, eg, `/page/:slug` etc.

**Comment by anuveyatsu** [comment]
Closing as FIXED, see the last comment above.
