### ISSUE TITLE
[Epic] MVP of the Frontend v3 app: home, showcase, org and search pages

### ISSUE THREAD

**Issue by lauragift21** [datopian/portal#9]
We want to build an MVP of a data portal frontend using Next.js. Data can be mocked or come from demo.ckan.org.

**MVP URL: https://portal.datopian1.now.sh/**

## Acceptance

This would be the core of an MVP

* [x] showcase
  * [x] dataset - can model layout on top part of datahub.io showcase pages
  * [x] resource page - a dedicated resource page
* [x] org profile page with list of datasets
* [x] search page for searching datasets (this could be dynamic/pure client side JS or could be server side)
* [x] home page (semi-optional for now in fact)

### Dataset page

* [x] A page with a list of datasets - with key information(title, description, etc)
* [x] All listed dataset leads to a new page with additional details on them.
* [x] Download feature - download / preview a dataset.
* [x] Search functionality - search for specific dataset using queries/keywords.

### DX side

* [ ] Instructions on how to customize the look and feel
* [ ] Instructions for more complex customization

MVP Part II (later)

* [x] create-portal-app app - a simple tool that scaffolds a working site
* [x] Integrate content from e.g. wordpress
* [ ] Google Analytics
* [ ] i18n

## Tasks

* [x] Boot a repo (or continue in branch of frontend-v2) https://github.com/datopian/portal
* [x] Stub a skeleton of the site (use next.js) https://portal.lauragift21.now.sh/
  * [x] README
* [x] Set up CI - use mocha i think
* [x] Set up CD
* [x] Show case page
* [x] write test to cover functionalities 

### Showcase page(s)

* [x] Stub a page `/@myorg/mydataset` that is empty
* [x] Copy over and convert nunjucks template from current frontend-v2 into jsx template (omitted all the preview stuff and resource display)
  * [x] Copy the preview material into a `/@myorg/mydataset/r/myresource` template
* [x] Refactor the JSX into templates so we move away from "inheritance" towards "composition" in how we build pages
  * [x] Simplest to start would be to move everything into a component "DatasetShowcaseCore"
* [x] Stub out the frontpage from frontend v2
* [x] Replace hard coded page data with hardcoded data in the "controller"
* [x] Replace hard coded data with real data from a live source ...

### Organization page(s)
* [ ] page with a list of all organizations
* [ ] page with a list of related datasets under an org.

How do we have `/@myorg/mydataset` => lookup data via fetch API from the right place?

We want `/@myorg` to be dynamic. Creating a dynamic route might work and setting up fetch API to pull data from the dynamic source (more research to be done here)

Next.js Data Fetching https://nextjs.org/docs/basic-features/data-fetching

### Backend

TODO:

* research graphql for Nextjs
* research reusing gatsby sources in Nextjs

**Comment by anuveyatsu** [comment]
Closing this as FIXED. Next items will be tracked in:

- v0.1 - #16 
- v0.2 - #33 
- v0.3 - #34

**Comment by rufuspollock** [comment]
@anuveyatsu can we make sure all the unchecked items in this issue *are* definitely captured iin one of the follow up issues (and could you note that in your fixed comment, when done).
